// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"

	"k8s.io/apimachinery/pkg/runtime"
)

func copyValue[T any](in *T) *T {
	if in == nil {
		return nil
	}
	data, err := json.Marshal(in)
	if err != nil {
		panic(err)
	}
	out := new(T)
	if err := json.Unmarshal(data, out); err != nil {
		panic(err)
	}
	return out
}

func (in *Project) DeepCopyInto(out *Project)          { *out = *copyValue(in) }
func (in *Project) DeepCopy() *Project                 { return copyValue(in) }
func (in *Project) DeepCopyObject() runtime.Object     { return in.DeepCopy() }
func (in *ProjectList) DeepCopyInto(out *ProjectList)  { *out = *copyValue(in) }
func (in *ProjectList) DeepCopy() *ProjectList         { return copyValue(in) }
func (in *ProjectList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Snapshot) DeepCopyInto(out *Snapshot)         { *out = *copyValue(in) }
func (in *Snapshot) DeepCopy() *Snapshot                { return copyValue(in) }
func (in *Snapshot) DeepCopyObject() runtime.Object     { return in.DeepCopy() }
func (in *SnapshotList) DeepCopyInto(out *SnapshotList) { *out = *copyValue(in) }
func (in *SnapshotList) DeepCopy() *SnapshotList        { return copyValue(in) }
func (in *SnapshotList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Build) DeepCopyInto(out *Build)            { *out = *copyValue(in) }
func (in *Build) DeepCopy() *Build                   { return copyValue(in) }
func (in *Build) DeepCopyObject() runtime.Object     { return in.DeepCopy() }
func (in *BuildList) DeepCopyInto(out *BuildList)    { *out = *copyValue(in) }
func (in *BuildList) DeepCopy() *BuildList           { return copyValue(in) }
func (in *BuildList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *BuildInfo) DeepCopyInto(out *BuildInfo)         { *out = *copyValue(in) }
func (in *BuildInfo) DeepCopy() *BuildInfo                { return copyValue(in) }
func (in *BuildInfo) DeepCopyObject() runtime.Object      { return in.DeepCopy() }
func (in *BuildInfoList) DeepCopyInto(out *BuildInfoList) { *out = *copyValue(in) }
func (in *BuildInfoList) DeepCopy() *BuildInfoList        { return copyValue(in) }
func (in *BuildInfoList) DeepCopyObject() runtime.Object  { return in.DeepCopy() }

func (in *RpmRepo) DeepCopyInto(out *RpmRepo)          { *out = *copyValue(in) }
func (in *RpmRepo) DeepCopy() *RpmRepo                 { return copyValue(in) }
func (in *RpmRepo) DeepCopyObject() runtime.Object     { return in.DeepCopy() }
func (in *RpmRepoList) DeepCopyInto(out *RpmRepoList)  { *out = *copyValue(in) }
func (in *RpmRepoList) DeepCopy() *RpmRepoList         { return copyValue(in) }
func (in *RpmRepoList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *BuildResource) DeepCopyInto(out *BuildResource) { *out = *copyValue(in) }
func (in *BuildResource) DeepCopy() *BuildResource        { return copyValue(in) }
func (in *BuildResource) DeepCopyObject() runtime.Object  { return in.DeepCopy() }
func (in *BuildResourceList) DeepCopyInto(out *BuildResourceList) {
	*out = *copyValue(in)
}
func (in *BuildResourceList) DeepCopy() *BuildResourceList   { return copyValue(in) }
func (in *BuildResourceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Job) DeepCopyInto(out *Job)              { *out = *copyValue(in) }
func (in *Job) DeepCopy() *Job                     { return copyValue(in) }
func (in *Job) DeepCopyObject() runtime.Object     { return in.DeepCopy() }
func (in *JobList) DeepCopyInto(out *JobList)      { *out = *copyValue(in) }
func (in *JobList) DeepCopy() *JobList             { return copyValue(in) }
func (in *JobList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *Runner) DeepCopyInto(out *Runner)           { *out = *copyValue(in) }
func (in *Runner) DeepCopy() *Runner                  { return copyValue(in) }
func (in *Runner) DeepCopyObject() runtime.Object     { return in.DeepCopy() }
func (in *RunnerList) DeepCopyInto(out *RunnerList)   { *out = *copyValue(in) }
func (in *RunnerList) DeepCopy() *RunnerList          { return copyValue(in) }
func (in *RunnerList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
