apiVersion: ebs/v1
kind: BuildConf
metadata:
  name: default
spec:
  targets:
    openEuler-22.03-LTS:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-riscv
    openEuler-22.03-LTS-SP1:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp1-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp1-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp1-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp1-riscv
    openEuler-22.03-LTS-SP2:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp2-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp2-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp2-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp2-riscv
    openEuler-22.03-LTS-SP3:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp3-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp3-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp3-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp3-riscv
    openEuler-mainline:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:mainline-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:mainline-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:mainline-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:mainline-riscv
        sw_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:mainline-sw
    openEuler-24.03-LTS-Next:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-next-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-next-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-next-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-next-riscv
    openEuler-24.03-LTS:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-riscv
    openEuler-22.03-LTS-SP4:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp4-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp4-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp4-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:22.03-lts-sp4-riscv
    openEuler-24.03-LTS-SP1:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp1-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp1-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp1-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp1-riscv
        sw_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp1-sw
    openEuler-24.03-LTS-SP2:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp2-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp2-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp2-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp2-riscv
        sw_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp2-sw
    openEuler-24.03-LTS-SP3:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp3-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp3-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp3-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp3-riscv
        sw_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp3-sw
    openEuler-24.03-LTS-SP4:
      arches:
        aarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp4-arm64
        x86_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp4-amd64
        loongarch64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp4-loongarch
        riscv64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp4-riscv
        sw_64:
          image: swr.cn-north-4.myhuaweicloud.com/eulermaker/openeuler:24.03-lts-sp4-sw
